const blocks=[
 {title:'HTML5, CSS e DOM',range:'Questões 1–20'},
 {title:'JavaScript, eventos e objetos',range:'Questões 21–40'},
 {title:'React, JSX, props e estado',range:'Questões 41–60'},
 {title:'API REST, Fetch, JWT e CRUD',range:'Questões 61–80'}
];
const q=(n,text,options,answer)=>({n,text,options,answer,type:'objective',block:Math.floor((n-1)/20)});
const d=(n,text,model)=>({n,text,model,type:'discursive',block:Math.floor((n-1)/20)});
const questions=[
q(1,'Qual alternativa apresenta apenas elementos semânticos do HTML5?',['<div>, <span> e <font>','<article>, <nav> e <aside>','<table>, <tr> e <td>','<body>, <script> e <style>','<input>, <label> e <button>'],1),
q(2,'A principal função do HTML é:',['Aplicar estilos visuais à página','Realizar consultas ao banco de dados','Estruturar e marcar o conteúdo da página','Controlar as regras de negócio do servidor','Gerenciar o sistema operacional'],2),
q(3,'Qual elemento HTML5 é utilizado para representar um conteúdo independente, como uma notícia ou publicação?',['<article>','<aside>','<footer>','<nav>','<span>'],0),
q(4,'Qual elemento é mais adequado para reunir links principais de navegação?',['<section>','<main>','<nav>','<article>','<header>'],2),
q(5,'Para vincular um arquivo CSS externo a uma página HTML, utiliza-se:',['<css>','<script>','<style>','<link>','<source>'],3),
q(6,'Em qual parte do HTML a tag <link> normalmente é colocada?',['Dentro de <footer>','Dentro de <body>','Dentro de <head>','Depois de </html>','Dentro de <main>'],2),
q(7,'Qual código define um fundo laranja e um texto branco?',['background-color: white; color: orange;','background-color: orange; color: white;','background: text-orange; color: white;','color-background: orange; text-color: white;','background-color: orange; font-color: white;'],1),
q(8,'Qual seletor CSS seleciona um elemento pelo seu id?',['.','#','*',':','@'],1),
q(9,'Qual seletor CSS seleciona elementos por classe?',['#classe','classe','.classe','@classe',':classe'],2),
q(10,'Considere:\n\np { color: blue; }\n\nEsse código:',['Altera todos os parágrafos para azul','Altera apenas o primeiro parágrafo','Altera o fundo da página','Cria um elemento chamado p','Altera todos os títulos'],0),
q(11,'A principal vantagem de utilizar CSS externo é:',['Impedir o uso de JavaScript','Separar conteúdo e apresentação','Substituir completamente o HTML','Executar código no servidor','Armazenar dados do usuário'],1),
q(12,'DOM significa:',['Data Object Management','Document Object Model','Dynamic Object Method','Document Operation Machine','Digital Organization Model'],1),
q(13,'O DOM representa uma página HTML como:',['Uma tabela relacional','Uma árvore de objetos e nós','Um arquivo binário','Uma imagem estática','Uma planilha'],1),
q(14,'Qual método obtém um elemento pelo seu identificador?',['document.getElementById()','document.getElementsByClassName()','document.createElement()','document.write()','document.appendChild()'],0),
q(15,'Qual método retorna o primeiro elemento que corresponde a um seletor CSS?',['getElementById()','getElementsByTagName()','querySelector()','querySelectorAll()','createElement()'],2),
d(16,'Explique a diferença entre HTML, CSS e JavaScript.','HTML estrutura e dá significado ao conteúdo; CSS controla sua apresentação visual; JavaScript acrescenta comportamento, lógica e interatividade.'),
d(17,'Explique o que é HTML semântico e apresente três exemplos de elementos semânticos.','HTML semântico usa elementos que descrevem o papel do conteúdo, favorecendo acessibilidade, SEO e manutenção. Exemplos: <header>, <nav> e <article>.'),
d(18,'Explique o que é o DOM e por que ele é importante para o JavaScript.','O DOM é a representação da página como uma árvore de nós e objetos. Por ele, o JavaScript consulta, cria, altera e remove elementos, atributos e conteúdo.'),
d(19,'Escreva um código JavaScript que selecione um elemento com id="titulo" e altere sua cor para azul.','const titulo = document.getElementById("titulo");\ntitulo.style.color = "blue";'),
d(20,'Explique a diferença entre getElementById, querySelector e querySelectorAll.','getElementById busca um elemento pelo id; querySelector aceita qualquer seletor CSS e retorna a primeira correspondência; querySelectorAll retorna uma NodeList com todas as correspondências.'),
q(21,'Qual palavra-chave declara uma variável cujo valor pode ser alterado?',['const','let','static','final','define'],1),q(22,'Qual palavra-chave impede uma nova atribuição à variável?',['var','let','const','change','fixed'],2),q(23,'Qual operador compara valor e tipo?',['=','==','===','!=','=>'],2),q(24,'Qual estrutura é utilizada para executar código conforme uma condição?',['if','import','return','const','className'],0),q(25,'Qual método exibe uma mensagem no console?',['console.write()','console.log()','document.log()','window.print()','alert.console()'],1),
q(26,'Qual é um exemplo válido de função JavaScript?',['function somar(a, b) { return a + b; }','func somar(a, b): a + b','def somar(a, b)','function = somar[a, b]','method somar(a, b)'],0),q(27,'Um evento de clique pode ser representado por:',['onSubmit','onLoad','onClick','onChange','onFocus'],2),q(28,'O evento normalmente disparado ao enviar um formulário é:',['onClick','onSubmit','onLoad','onMouseOver','onKeyUp'],1),q(29,'O evento disparado quando a página é carregada é:',['onSubmit','onChange','onLoad','onInput','onBlur'],2),q(30,'Qual método é recomendado para associar eventos em JavaScript nativo?',['setEvent()','appendEvent()','addEventListener()','createEventHandler()','eventConnect()'],2),
q(31,'O método preventDefault() é utilizado para:',['Excluir um elemento','Impedir o comportamento padrão de um evento','Criar um novo evento','Atualizar a página','Encerrar o navegador'],1),q(32,'Qual propriedade obtém o conteúdo digitado em um campo <input>?',['innerHTML','value','textContent','name','className'],1),q(33,'Qual propriedade pode substituir o conteúdo HTML interno de um elemento?',['innerHTML','value','href','src','id'],0),q(34,'Qual objeto nativo é utilizado para cálculos matemáticos?',['Date','Math','RegExp','StringList','NumberObject'],1),q(35,'Qual objeto representa datas e horários?',['Calendar','Time','Date','Clock','Moment'],2),
d(36,'Explique o que são eventos em JavaScript e apresente três exemplos.','Eventos são ocorrências detectadas pelo navegador às quais o código pode reagir. Exemplos: click, submit e load.'),
d(37,'Escreva um código que leia o valor de um campo com id="nome" e exiba esse valor em um elemento com id="resultado" após o clique em um botão.','botao.addEventListener("click", () => {\n  const nome = document.getElementById("nome").value;\n  document.getElementById("resultado").textContent = nome;\n});'),
d(38,'Explique a diferença entre innerHTML, textContent e value.','innerHTML lê ou grava marcação HTML interna; textContent trabalha com texto puro; value representa o valor de controles como input, select e textarea.'),
d(39,'Explique o que são objetos nativos do JavaScript e descreva as funções de Math, Date e RegExp.','Objetos nativos são recursos embutidos na linguagem. Math oferece operações matemáticas; Date manipula datas e horários; RegExp cria padrões para busca e validação de texto.'),
d(40,'Analise o código:\n\nconst lista = document.getElementById("lista");\nconst itens = ["Item 1", "Item 2", "Item 3"];\n\nitens.forEach((item) => {\n  lista.innerHTML += `<li>${item}</li>`;\n});\n\nExplique o fluxo completo de execução.','O elemento #lista é selecionado; o array recebe três strings; forEach percorre cada string; em cada volta uma <li> é interpolada e acrescentada ao HTML existente da lista.'),
q(41,'React é:',['Um sistema operacional','Uma biblioteca JavaScript para interfaces','Um banco de dados','Uma linguagem de marcação','Um servidor HTTP'],1),q(42,'JSX permite:',['Escrever SQL dentro do CSS','Escrever uma sintaxe semelhante a HTML dentro do JavaScript','Executar Java no navegador','Criar bancos de dados','Substituir o Node.js'],1),q(43,'Qual é uma forma válida de declarar um componente funcional?',['function Menu() { return <nav>Menu</nav>; }','component Menu { nav Menu }','function = Menu(nav);','class Menu => nav;','create Menu <nav>;'],0),q(44,'Em React, o nome de um componente deve começar, normalmente, com:',['Número','Letra minúscula','Letra maiúscula','Caractere especial','Ponto'],2),q(45,'Props são utilizadas para:',['Armazenar arquivos no navegador','Passar dados de um componente para outro','Criar tabelas no banco','Reiniciar o servidor','Substituir o estado'],1),
q(46,'Dado:\n\nfunction Titulo(props) { return <h1>{props.texto}</h1>; }\n\nQual uso está correto?',['<Titulo texto="Olá" />','<Titulo = "Olá">','Titulo.props("Olá")','<texto Titulo="Olá" />','props.Titulo = "Olá"'],0),q(47,'Qual hook é utilizado para controlar estado em componentes funcionais?',['useEffect','useState','useFetch','useProps','useComponent'],1),q(48,'Considere:\n\nconst [contador, setContador] = useState(0);\n\nO valor inicial de contador é:',['null','1','0','undefined','false'],2),q(49,'Para alterar o estado anterior, deve-se utilizar:',['Atribuição direta','A função atualizadora retornada pelo hook','document.write()','innerHTML','window.reload()'],1),q(50,'Qual código atualiza corretamente o contador?',['contador = contador + 1','setContador(contador + 1)','useState(contador + 1)','props.contador++','contador.update()'],1),
q(51,'Em JSX, o atributo HTML class é escrito como:',['cssClass','className','styleClass','classId','htmlClass'],1),q(52,'Um evento de clique em React é escrito como:',['onclick','on-click','onClick','clickEvent','click'],2),q(53,'Qual alternativa associa corretamente uma função a um clique?',['<button onClick={salvar}>Salvar</button>','<button onclick="salvar()">Salvar</button>','<button click={salvar()}>Salvar</button>','<button onClick="salvar">Salvar</button>','<button event={salvar}>Salvar</button>'],0),q(54,'Um componente controlado possui:',['Valores gerenciados pelo estado do React','Apenas CSS externo','Dados obrigatoriamente no LocalStorage','Somente elementos estáticos','Nenhum evento'],0),q(55,'Em um formulário React, o evento utilizado normalmente para atualizar o estado enquanto o usuário digita é:',['onLoad','onChange','onSubmit','onMouseOver','onError'],1),
d(56,'Explique o que são componentes React e por que eles favorecem reutilização e organização.','Componentes são unidades independentes de interface e comportamento. Eles encapsulam responsabilidades, podem ser combinados e reutilizados, deixando a aplicação modular e mais fácil de manter.'),d(57,'Explique o conceito de props e apresente um exemplo de passagem de dados entre componentes.','Props são dados imutáveis recebidos do componente pai. Exemplo: <Saudacao nome="Ana" /> e, no filho, function Saudacao({nome}) { return <p>Olá, {nome}</p>; }.'),d(58,'Explique o funcionamento do useState.','useState cria uma variável de estado e uma função atualizadora. Ao chamar a atualizadora, o React agenda nova renderização com o valor atualizado.'),
d(59,'Identifique e corrija o erro:\n\nconst [user, setUser] = useState({ username: "", email: "" });\nconst handleChange = (e) => {\n  const { name, value } = e.target;\n  user.username = value;\n};','O estado foi mutado diretamente e o campo name foi ignorado. Correção: setUser(prev => ({ ...prev, [name]: value }));'),d(60,'Crie um componente React com um campo de texto, um botão e uma área de resultado. Ao clicar no botão, o texto digitado deve aparecer na tela.','function App() {\n const [texto,setTexto]=useState(""); const [resultado,setResultado]=useState("");\n return <><input value={texto} onChange={e=>setTexto(e.target.value)} /><button onClick={()=>setResultado(texto)}>Exibir</button><p>{resultado}</p></>;\n}'),
q(61,'Consumir uma API significa:',['Criar estilos CSS','Enviar e receber dados de outro sistema','Instalar o navegador','Criar tags HTML','Alterar arquivos locais do servidor manualmente'],1),q(62,'Qual função nativa do navegador é utilizada para realizar requisições HTTP?',['requestAPI()','fetch()','http()','ajaxNative()','apiCall()'],1),q(63,'O método HTTP utilizado normalmente para consultar dados é:',['POST','DELETE','GET','PUT','PATCH'],2),q(64,'O método normalmente utilizado para cadastrar um recurso é:',['GET','POST','DELETE','OPTIONS','HEAD'],1),q(65,'O método normalmente utilizado para substituir completamente um recurso é:',['GET','POST','PATCH','PUT','DELETE'],3),
q(66,'O método normalmente utilizado para atualizar parcialmente um recurso é:',['PATCH','GET','POST','DELETE','HEAD'],0),q(67,'O método utilizado para remover um recurso é:',['GET','PATCH','POST','DELETE','TRACE'],3),q(68,'Requisições a APIs são assíncronas porque:',['Não utilizam JavaScript','A resposta pode levar tempo para chegar','Executam apenas no CSS','Não possuem retorno','Sempre bloqueiam o navegador'],1),q(69,'async/await ajuda a:',['Criar estilos','Organizar código assíncrono de maneira mais legível','Criar elementos HTML automaticamente','Substituir uma API','Criar um banco de dados'],1),q(70,'Para converter uma resposta JSON do fetch, utiliza-se normalmente:',['response.toString()','response.json()','response.parseHTML()','JSON.response()','fetch.json(response)'],1),
q(71,'LocalStorage é utilizado para:',['Persistir pequenos dados no navegador','Executar consultas SQL','Salvar arquivos no servidor','Criar componentes React','Proteger completamente dados sensíveis'],0),q(72,'Qual método armazena dados no LocalStorage?',['localStorage.save()','localStorage.setItem()','localStorage.add()','localStorage.insert()','localStorage.push()'],1),q(73,'Qual método recupera dados do LocalStorage?',['localStorage.getItem()','localStorage.read()','localStorage.find()','localStorage.select()','localStorage.open()'],0),q(74,'Qual método remove um item específico do LocalStorage?',['localStorage.delete()','localStorage.removeItem()','localStorage.drop()','localStorage.removeAll()','localStorage.destroy()'],1),q(75,'JWT é utilizado principalmente para:',['Estilizar páginas','Representar autenticação e autorização por token','Criar bancos relacionais','Substituir o HTML','Compilar o React'],1),
d(76,'Explique as diferenças entre GET, POST, PUT, PATCH e DELETE, apresentando um exemplo de uso para cada método.','GET consulta (listar usuários); POST cria (novo usuário); PUT substitui todo um recurso; PATCH altera parte dele (somente e-mail); DELETE remove o recurso.'),d(77,'Explique como funciona o fluxo de login com JWT, desde o envio das credenciais até o acesso a uma rota protegida.','O cliente envia credenciais por HTTPS; o servidor valida e assina um JWT; o cliente armazena o token e o envia como Bearer nas próximas requisições; o servidor verifica assinatura, validade e permissões antes de liberar a rota.'),
d(78,'Analise:\n\nasync function listarUsuarios() {\n  const token = localStorage.getItem("token");\n  const resposta = await fetch("http://localhost:8080/usuarios", {\n    method: "GET",\n    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }\n  });\n  const dados = await resposta.json();\n  return dados;\n}\n\nExplique cada etapa do código.','A função assíncrona recupera o token local, faz GET aguardando a resposta e envia os cabeçalhos JSON e Bearer. Depois aguarda a conversão do corpo para JavaScript e devolve os dados. Em produção, também deve verificar resposta.ok e tratar erros.'),
d(79,'Explique como estado, eventos, componentes e comunicação com API trabalham juntos em um formulário React de cadastro de usuários.','O componente renderiza campos controlados pelo estado. Eventos onChange atualizam esse estado e onSubmit valida e envia os dados à API. A resposta atualiza estados de carregamento, erro ou sucesso e pode atualizar a lista exibida por outros componentes.'),d(80,'Desenvolva, em pseudocódigo ou JavaScript/React, o fluxo completo de um CRUD de usuários com autenticação, incluindo: login; armazenamento do token; listagem; cadastro; edição; exclusão; logout.','login: POST /login → salvar token; listar: GET /usuarios com Bearer; cadastrar: POST /usuarios; editar: PUT/PATCH /usuarios/:id; excluir: DELETE /usuarios/:id; em todas as rotas protegidas enviar Authorization. logout: remover token e redirecionar ao login. Tratar resposta.ok e erros.'),
];

const explanationList=[
'Elementos como article, nav e aside descrevem a função do conteúdo; div e span são genéricos.','HTML organiza e marca o conteúdo; aparência é responsabilidade do CSS e comportamento do JavaScript.','article representa conteúdo autônomo, como notícia ou postagem.','nav identifica uma seção de links de navegação.','link com rel="stylesheet" conecta uma folha CSS externa.','Recursos e metadados do documento ficam normalmente dentro de head.','background-color define o fundo e color define a cor do texto.','O prefixo de um seletor de id no CSS é #.','O ponto é o prefixo usado para selecionar uma classe no CSS.','O seletor de tipo p corresponde a todos os parágrafos.','CSS externo separa estrutura e apresentação e pode ser reutilizado em várias páginas.','DOM significa Document Object Model.','O navegador representa elementos e textos em uma árvore hierárquica de nós.','getElementById busca diretamente o elemento que possui o id informado.','querySelector aceita um seletor CSS e retorna somente a primeira correspondência.',
'let cria uma variável de escopo de bloco que pode receber outro valor.','const impede uma nova atribuição à variável.','=== exige igualdade tanto de valor quanto de tipo.','if executa um bloco quando sua condição é verdadeira.','console.log envia mensagens e valores ao console do navegador.','Essa alternativa usa a sintaxe válida function nome(parâmetros) e retorna o resultado.','onClick representa uma reação ao clique do usuário.','submit é o evento próprio do envio de um formulário.','load ocorre quando a página e seus recursos terminam de carregar.','addEventListener registra ouvintes sem substituir os demais.','preventDefault cancela uma ação padrão, como o recarregamento no envio de formulário.','value contém o valor atual de campos como input.','innerHTML lê ou substitui a marcação interna do elemento.','Math reúne funções e constantes para operações matemáticas.','Date cria e manipula datas e horários.',
'React é uma biblioteca JavaScript baseada em componentes para construir interfaces.','JSX permite descrever a interface com marcação semelhante a HTML dentro do JavaScript.','Um componente funcional é uma função que retorna elementos React ou JSX.','A inicial maiúscula diferencia componentes personalizados das tags HTML nativas.','Props são entradas passadas normalmente do componente pai para o filho.','texto="Olá" envia a prop texto, lida no componente como props.texto.','useState adiciona estado local a um componente funcional.','O argumento de useState é o valor inicial; nesse caso, zero.','A função atualizadora notifica o React e provoca a renderização necessária.','setContador é a função atualizadora fornecida pelo useState.','Em JSX, class é representado pela propriedade className.','Eventos JSX usam camelCase; por isso, escreve-se onClick.','onClick deve receber a referência da função entre chaves para executá-la apenas no clique.','Em um campo controlado, o valor vem do estado do React.','onChange mantém o estado sincronizado com o valor digitado.',
'Consumir uma API é trocar dados com outro sistema por meio de requisições.','fetch é a API nativa moderna do navegador para requisições HTTP.','GET é destinado à leitura ou consulta de recursos.','POST normalmente envia dados para criar um novo recurso.','PUT envia uma representação completa para substituir um recurso.','PATCH altera somente parte de um recurso.','DELETE solicita a remoção do recurso indicado pela URL.','A rede pode demorar; a execução assíncrona aguarda sem bloquear a interface.','async/await torna o trabalho com Promises mais sequencial e legível.','response.json() interpreta o corpo JSON e retorna uma Promise com os dados.','LocalStorage persiste pequenos pares de chave e valor no navegador, mas não protege segredos.','setItem(chave, valor) grava ou substitui um item.','getItem(chave) recupera o valor ou retorna null.','removeItem(chave) apaga somente o item indicado.','JWT é um token assinado usado para representar identidade e permissões.'
];
const objectiveNumbers=[...Array(15)].map((_,i)=>i+1).concat([...Array(15)].map((_,i)=>i+21),[...Array(15)].map((_,i)=>i+41),[...Array(15)].map((_,i)=>i+61));
const explanations=Object.fromEntries(objectiveNumbers.map((n,i)=>[n,explanationList[i]]));
const KEY='devsimulado-state-v1';
let state={answers:{},review:[],current:0,elapsed:0,started:false,finished:false};
try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
let timerId;
const $=s=>document.querySelector(s);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const escapeHtml=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
function start(resume=false){if(!resume){state={answers:{},review:[],current:0,elapsed:0,started:true,finished:false}}else state.started=true;save();show('quiz');render();startTimer()}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{state.elapsed++;$('#timer').textContent=formatTime(state.elapsed);if(state.elapsed%10===0)save()},1000)}
const formatTime=s=>[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':');
function answered(q){const a=state.answers[q.n];return q.type==='objective'?Number.isInteger(a):!!a?.trim()}
function progress(){return questions.filter(answered).length}
function renderSidebar(){const done=progress();$('#progressPercent').textContent=Math.round(done/80*100)+'%';$('#progressRing').style.setProperty('--p',done/80*100);$('#blockList').innerHTML=blocks.map((b,i)=>{const count=questions.filter(x=>x.block===i&&answered(x)).length;return `<div class="block-item ${questions[state.current].block===i?'active':''}" data-block="${i}"><span class="num">0${i+1}</span><div><strong>${b.title}</strong><small>${count}/20 respondidas</small><div class="mini-progress"><i style="width:${count*5}%"></i></div></div></div>`}).join('');document.querySelectorAll('.block-item').forEach(x=>x.onclick=()=>{state.current=+x.dataset.block*20;save();render()})}
function render(){const item=questions[state.current],answer=state.answers[item.n];renderSidebar();$('#blockKicker').textContent=`BLOCO 0${item.block+1} • ${blocks[item.block].range}`;$('#blockTitle').textContent=blocks[item.block].title;$('#currentNum').textContent=item.n;$('#reviewBtn').classList.toggle('active',state.review.includes(item.n));$('#reviewBtn').textContent=(state.review.includes(item.n)?'★':'☆')+' Marcar para revisão';$('#prevBtn').disabled=state.current===0;$('#nextBtn').textContent=state.current===79?'Finalizar →':'Próxima →';
 const card=$('#questionCard');
 if(item.type==='objective'){const has=Number.isInteger(answer),right=answer===item.answer,letter=String.fromCharCode(65+item.answer);card.innerHTML=`<span class="question-label">QUESTÃO ${String(item.n).padStart(2,'0')} • OBJETIVA</span><h3>${escapeHtml(item.text)}</h3><div class="options">${item.options.map((o,i)=>`<div class="option ${answer===i?'selected':''} ${has&&i===item.answer?'correct':''} ${has&&answer===i&&i!==item.answer?'wrong':''}" data-option="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${escapeHtml(o)}</span></div>`).join('')}</div>${has?`<div class="answer-feedback ${right?'feedback-correct':'feedback-wrong'}"><div class="feedback-title"><span>${right?'✓':'×'}</span><strong>${right?'Resposta correta!':'Resposta incorreta'}</strong></div><p>${right?'Isso mesmo.':`A alternativa correta é <b>${letter}</b>.`} ${escapeHtml(explanations[item.n])}</p></div>`:''}`;card.querySelectorAll('.option').forEach(o=>o.onclick=()=>{state.answers[item.n]=+o.dataset.option;save();render()})}
 else{card.innerHTML=`<span class="question-label">QUESTÃO ${String(item.n).padStart(2,'0')} • DISCURSIVA</span><h3>${escapeHtml(item.text)}</h3><textarea id="essay" placeholder="Escreva sua resposta aqui...">${escapeHtml(answer||'')}</textarea><div class="answer-hint">Sua resposta é salva automaticamente no navegador.</div>${state.finished?`<div class="model-answer"><strong>Resposta-modelo</strong><br>${escapeHtml(item.model).replace(/\n/g,'<br>')}</div>`:''}`;$('#essay').oninput=e=>{state.answers[item.n]=e.target.value;save();renderSidebar()}}
}
function finish(force=false){const missing=80-progress();if(!force){$('#dialogText').textContent=missing?`Você ainda tem ${missing} ${missing===1?'questão sem resposta':'questões sem resposta'}. Você pode finalizar agora ou continuar.`:'Todas as questões foram respondidas. Pronto para ver o resultado?';$('#confirmDialog').showModal();return}state.finished=true;save();clearInterval(timerId);showResults()}
function showResults(){show('results');const objective=questions.filter(x=>x.type==='objective'),correct=objective.filter(x=>state.answers[x.n]===x.answer).length,essays=questions.filter(x=>x.type==='discursive'&&answered(x)).length;const score=correct+essays*2;$('#scoreValue').textContent=score;$('#scoreRing').style.setProperty('--p',score);$('#resultMessage').textContent=score>=85?'Excelente trabalho!':score>=70?'Mandou bem!':score>=50?'Bom começo!':'Hora de reforçar a base!';$('#resultBlocks').innerHTML=blocks.map((b,i)=>{const obj=objective.filter(x=>x.block===i),c=obj.filter(x=>state.answers[x.n]===x.answer).length,e=questions.filter(x=>x.block===i&&x.type==='discursive'&&answered(x)).length,s=c+e*2;return `<div class="result-block"><small>BLOCO 0${i+1}</small><h3>${b.title}</h3><strong>${s}</strong><span> / 25 pontos</span><div class="result-bar"><i style="width:${s*4}%"></i></div></div>`}).join('')}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
$('#startBtn').onclick=()=>start(false);$('#resumeBtn').onclick=()=>start(true);$('#prevBtn').onclick=()=>{state.current--;save();render()};$('#nextBtn').onclick=()=>{if(state.current===79)finish();else{state.current++;save();render()}};$('#reviewBtn').onclick=()=>{const n=questions[state.current].n,i=state.review.indexOf(n);i<0?state.review.push(n):state.review.splice(i,1);save();render();toast(i<0?'Marcada para revisão':'Marcação removida')};$('#finishBtn').onclick=()=>finish();$('#cancelFinish').onclick=()=>$('#confirmDialog').close();$('#confirmFinish').onclick=()=>{$('#confirmDialog').close();finish(true)};$('#restartBtn').onclick=()=>{if(confirm('Deseja apagar as respostas e começar novamente?'))start(false)};$('#reviewErrorsBtn').onclick=()=>{const wrong=questions.findIndex(x=>x.type==='objective'&&state.answers[x.n]!==x.answer);state.current=wrong<0?0:wrong;show('quiz');render()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('devsimulado-theme',document.body.classList.contains('light')?'light':'dark')};
if(localStorage.getItem('devsimulado-theme')==='light')document.body.classList.add('light');
$('#timer').textContent=formatTime(state.elapsed);if(state.started&&!state.finished)$('#resumeBtn').hidden=false;if(state.finished){$('#resumeBtn').hidden=false;$('#resumeBtn').textContent='Ver meu último resultado';$('#resumeBtn').onclick=showResults}
